pluginManagement {
    repositories {
        google {
            content {
                includeGroupAndSubgroups("com.android")
                includeGroupAndSubgroups("com.google")
                includeGroupAndSubgroups("androidx")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google {
            content {
                includeGroupAndSubgroups("com.android")
                includeGroupAndSubgroups("com.google")
                includeGroupAndSubgroups("androidx")
            }
        }
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
        flatDir { dirs("${rootProject.projectDir}/core/gopenpgp/libs") }
    }
}

rootProject.name = "Passbolt"

fun projectModule(
    name: String,
    directory: String = "",
) {
    include(":$name")
    project(":$name").projectDir = file(directory + name)
}

fun coreModule(name: String) = projectModule(name, "core/")

fun featureModule(name: String) = projectModule(name, "features/")

fun serviceModule(name: String) = projectModule(name, "services/")

fun modelModule(name: String) = projectModule(name, "model/")

projectModule("app")

coreModule("architecture")
coreModule("accounts")
coreModule("networking")
coreModule("gopenpgp")
coreModule("coreui")
coreModule("common")
coreModule("navigation")
coreModule("qrscan")
coreModule("database")
coreModule("security")
coreModule("users")
coreModule("logger")
coreModule("localization")
coreModule("commontest")
coreModule("passwordgenerator")
coreModule("fulldatarefresh")
coreModule("resourcetypes")
coreModule("notifications")
coreModule("autofill")
coreModule("envinfo")
coreModule("idlingresource")
coreModule("otpcore")
coreModule("tags")
coreModule("encryptedstorage")
coreModule("passphrasememorycache")
coreModule("clipboard")
coreModule("testtags")

featureModule("startup")
featureModule("setup")
featureModule("autofillresources")
featureModule("authentication")
featureModule("main")
featureModule("home")
featureModule("settings")
featureModule("resourcedetails")
featureModule("accountdetails")
featureModule("permissions")
featureModule("locationdetails")
featureModule("createfolder")
featureModule("folderdetails")
featureModule("groupdetails")
featureModule("tagsdetails")
featureModule("featureflagserror")
featureModule("helpmenu")
featureModule("logs")
featureModule("resourcemoremenu")
featureModule("transferaccounttoanotherdevice")
featureModule("otp")
featureModule("resourcepicker")
featureModule("scanotp")
featureModule("otpmoremenu")
featureModule("createresourcemenu")
featureModule("resourceform")
featureModule("metadatakeytrust")
featureModule("accessibilitypolicies")

serviceModule("linksapi")
serviceModule("pwnedpasswordsapi")

modelModule("dto")
modelModule("uimodel")
modelModule("mappers")
modelModule("entity")
modelModule("serializers")
modelModule("supportedresourcetypes")
modelModule("jsonmodel")

include(":passwordpolicies-domain")
project(":passwordpolicies-domain").projectDir = file("domain/passwordpolicies")
include(":passwordpolicies-data")
project(":passwordpolicies-data").projectDir = file("data/passwordpolicies")
include(":preferences-domain")
project(":preferences-domain").projectDir = file("domain/preferences")
include(":preferences-data")
project(":preferences-data").projectDir = file("data/preferences")
include(":rbac-domain")
project(":rbac-domain").projectDir = file("domain/rbac")
include(":rbac-data")
project(":rbac-data").projectDir = file("data/rbac")
include(":mobiletransfer-domain")
project(":mobiletransfer-domain").projectDir = file("domain/mobiletransfer")
include(":mobiletransfer-data")
project(":mobiletransfer-data").projectDir = file("data/mobiletransfer")
include(":favourites-domain")
project(":favourites-domain").projectDir = file("domain/favourites")
include(":favourites-data")
project(":favourites-data").projectDir = file("data/favourites")
include(":passwordexpiry-domain")
project(":passwordexpiry-domain").projectDir = file("domain/passwordexpiry")
include(":passwordexpiry-data")
project(":passwordexpiry-data").projectDir = file("data/passwordexpiry")
include(":users-domain")
project(":users-domain").projectDir = file("domain/users")
include(":users-data")
project(":users-data").projectDir = file("data/users")
include(":share-domain")
project(":share-domain").projectDir = file("domain/share")
include(":share-data")
project(":share-data").projectDir = file("data/share")
include(":mfa-domain")
project(":mfa-domain").projectDir = file("domain/mfa")
include(":mfa-data")
project(":mfa-data").projectDir = file("data/mfa")
include(":resourcetypes-domain")
project(":resourcetypes-domain").projectDir = file("domain/resourcetypes")
include(":resourcetypes-data")
project(":resourcetypes-data").projectDir = file("data/resourcetypes")
include(":featureflags-domain")
project(":featureflags-domain").projectDir = file("domain/featureflags")
include(":featureflags-data")
project(":featureflags-data").projectDir = file("data/featureflags")
include(":folders-domain")
project(":folders-domain").projectDir = file("domain/folders")
include(":folders-data")
project(":folders-data").projectDir = file("data/folders")
include(":groups-domain")
project(":groups-domain").projectDir = file("domain/groups")
include(":groups-data")
project(":groups-data").projectDir = file("data/groups")
include(":privatekey-domain")
project(":privatekey-domain").projectDir = file("domain/privatekey")
include(":privatekey-data")
project(":privatekey-data").projectDir = file("data/privatekey")
include(":resources-domain")
project(":resources-domain").projectDir = file("domain/resources")
include(":resources-data")
project(":resources-data").projectDir = file("data/resources")
include(":secrets-domain")
project(":secrets-domain").projectDir = file("domain/secrets")
include(":secrets-data")
project(":secrets-data").projectDir = file("data/secrets")
include(":metadata-domain")
project(":metadata-domain").projectDir = file("domain/metadata")
include(":metadata-data")
project(":metadata-data").projectDir = file("data/metadata")
include(":auth-domain")
project(":auth-domain").projectDir = file("domain/auth")
include(":auth-data")
project(":auth-data").projectDir = file("data/auth")
include(":accounts-domain")
project(":accounts-domain").projectDir = file("domain/accounts")
include(":accounts-data")
project(":accounts-data").projectDir = file("data/accounts")
include(":inappreview-domain")
project(":inappreview-domain").projectDir = file("domain/inappreview")
include(":inappreview-data")
project(":inappreview-data").projectDir = file("data/inappreview")
include(":biometrickey-domain")
project(":biometrickey-domain").projectDir = file("domain/biometrickey")
include(":biometrickey-data")
project(":biometrickey-data").projectDir = file("data/biometrickey")
