plugins {
    alias libs.plugins.android.library
}

dependencies {
    implementation project(':common')
    implementation project(':coreui')
    implementation project(':localization')
    implementation project(':navigation')
    implementation project(':ui')
    implementation project(':jsonmodel')

    implementation platform(libs.koin.bom)
    implementation libs.koin

    testImplementation libs.junit
    testImplementation libs.truth
    testImplementation libs.mockito.kotlin
}

android {
    namespace = "com.passbolt.mobile.android.core.autofill"

    buildFeatures {
        buildConfig = true
    }
}

kotlin {
    jvmToolchain(17)
}
